Refactor infrastructure and add github workflows.
OpenUxAS anod support is now a proper python module named `uxas`. Paths
within the uxas module are refactored. The module directory under
infrastructure/uxas has the expected layout for a python module project
and includes a tox.ini file so that tox can be used for development and
in CI.

infrastructure/install is now a script that calls into python scripts in
infrastructure/install-libexec; these are not a proper python module,
since that would create a chicken-and-egg problem. There is a tox.ini
file here, too, for development and CI.

infrastructure/bootstrap is the new bootstrap script, which is less
useful now but still usable.

Scripts have been updated as needed to take advantage of the uxas python
module. In particular, anod and run-example check for the python venv
and call into infrastructure/install if needed.

diff --git a/anod b/anod
--- a/anod
+++ b/anod
@@ -1,6 +1,11 @@
-#! /bin/bash
+#! /usr/bin/env bash
 #
 # Anod wrapper script.
+#
+# Note that this script is meant to either be run directly by the user or is
+# meant to be sourced. In the former case, we can assume we're running bash. In
+# the latter case, we're in the user's current shell. We support bash and zsh.
+# Support for ksh is incomplete.
 
 # Script location
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@@ -8,17 +13,43 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 # Load global paths
 source "${SCRIPT_DIR}/infrastructure/paths.sh"
 
-# Activate the virtual environment
-source "${VPYTHON_ACTIVATE}"
-
-ANOD_SCRIPT="${INFRASTRUCTURE_DIR}/libexec/anod.py"
-
 
 # Determine if we're being sourced (BASH, KSH, and ZSH compliant):
 ([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] || 
  [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
     printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] || 
  [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)) && sourced=1 || sourced=0
+
+
+if [ -f ${VPYTHON_ACTIVATE} ]; then
+    # Activate the virtual environment
+    source "${VPYTHON_ACTIVATE}"
+else
+    # This is here so that make doesn't halt with no visible output while
+    # anod tries to install itself.
+    if [[ $1 == "--no-install" ]]; then
+        exit 1
+    fi
+
+    echo "It looks like this is your first time running anod for this OpenUxAS clone."
+    echo "Let's install the infrastructure support on which anod depends."
+    echo " "
+
+    ${INFRASTRUCTURE_DIR}/install
+
+    if [ -f ${VPYTHON_ACTIVATE} ]; then
+        source "${VPYTHON_ACTIVATE}"
+    else
+        echo "Installing infrastructure support appears to have failed."
+        
+        if [ $source -eq 0 ]; then
+            exit 1
+        fi
+    fi
+fi
+
+
+ANOD_SCRIPT="from uxas.cli.anod import do_cli; exit(do_cli())"
 
 # If we're not being sourced, then try to run the command the user requested.
 if [ $sourced -eq 0 ]; then
@@ -35,7 +66,7 @@ if [ $sourced -eq 0 ]; then
             ;;
 
         *)
-            python3 "${ANOD_SCRIPT}" $@
+            SHELL=/bin/bash python3 -c "${ANOD_SCRIPT}" $@
             ;;
     esac
 else
@@ -43,11 +74,11 @@ else
     function anod {
         case $1 in
             build)
-                SHELL=/bin/bash python3 "${ANOD_SCRIPT}" build "${@:2}"
+                SHELL=/bin/bash python3 -c "${ANOD_SCRIPT}" build "${@:2}"
                 ;;
 
             setenv)
-                eval "$( python3 "${ANOD_SCRIPT}" printenv "${@:2}" )"
+                eval "$( python3 -c "${ANOD_SCRIPT}" printenv "${@:2}" )"
                 ;;
 
             reset)
@@ -56,7 +87,8 @@ else
                 ;;
             
             *)
-                python3 "${ANOD_SCRIPT}" $@
+                echo $OPENUXAS_ROOT
+                python3 -c "${ANOD_SCRIPT}" $@
                 ;;
         esac
 
diff --git a/run-example b/run-example
--- a/run-example
+++ b/run-example
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/env bash
 #
 # run-example wrapper script.
 
@@ -8,7 +8,22 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 # Load global paths
 source "${SCRIPT_DIR}/infrastructure/paths.sh"
 
-# Activate the virtual environment
-source "${VPYTHON_ACTIVATE}"
+if [ -f ${VPYTHON_ACTIVATE} ]; then
+    # Activate the virtual environment
+    source "${VPYTHON_ACTIVATE}"
+else
+    echo "It looks like this is your first time running anod for this OpenUxAS clone."
+    echo "Let's install the infrastructure support on which anod depends."
+    echo " "
+
+    ${INFRASTRUCTURE_DIR}/install
+
+    if [ -f ${VPYTHON_ACTIVATE} ]; then
+        source "${VPYTHON_ACTIVATE}"
+    else
+        echo "Installing infrastructure support appears to have failed."
+        exit 1
+    fi
+fi
 
 python3 "${INFRASTRUCTURE_DIR}/run-example.py" $@
